apis:
  annotations:
    root: ./src/annotations-api.openapi.yaml
    output: ./out/annotations-api.openapi.yaml
  data-pipelines:
    root: ./src/data-pipelines-api.openapi.yaml
    output: ./out/data-pipelines-api.openapi.yaml
  export:
    root: ./src/event-export-api.openapi.yaml
    output: ./out/event-export-api.openapi.yaml
  gdpr:
    root: ./src/gdpr-api-2.openapi.yaml
    output: ./out/gdpr-api-2.openapi.yaml
  identity:
    root: ./src/identity-api.openapi.yaml
    output: ./out/identity-api.openapi.yaml
  ingestion:
    root: ./src/ingestion-api.openapi.yaml
    output: ./out/ingestion-api.openapi.yaml
  lexicon-schemas:
    root: ./src/lexicon-schemas-api.openapi.yaml
    output: ./out/lexicon-schemas-api.openapi.yaml
  query:
    root: ./src/query-api.openapi.yaml
    output: ./out/query-api.openapi.yaml
  service-accounts:
    root: ./src/service-accounts-api.openapi.yaml
    output: ./out/service-accounts-api.openapi.yaml
  warehouse-connectors:
    root: ./src/warehouse-connectors-api.openapi.yaml
    output: ./out/warehouse-connectors-api.openapi.yaml

extends:
  - recommended

rules:
  info-license: off
  paths-kebab-case: off
  boolean-parameter-prefixes: off
  operation-description: off

  # Todo: fix these offenders
  operation-tag-defined: off
  parameter-description: off
