openapi: 3.0.2
info:
  title: GDPR API
  description: >-
    The following retrieval and deletion API is made for GDPR and CCPA compliance.
  contact:
    url: 'https://mixpanel.com/get-support'
  version: 3.0.0
servers:
  - $ref: ./common/app-api.yaml#/server
security:
  - ServiceAccount: []
tags:
  - name: Cancel Deletion
    description: Cancels an existing deletion task
  - name: Check Status of Retrieval
    description: Checks the status of a data retrieval job
  - name: Check Status of a Deletion Task
    description: Checks the status of an existing deletion task
  - name: Create Retrieval
    description: Creates a data retrieval job
  - name: Create a Deletion Task
    description: Creates a task that specifies a list of users in a particular project to delete
paths:
  /api/app/data-retrievals/v3.0:
    post:
      parameters:
      - name: token
        in: query
        description: 'Your project token'
        required: true
        schema:
          type: string
      operationId: create-retrieval
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                distinct_ids:
                  $ref: '#/components/schemas/DistinctIds'
                compliance_type:
                  description: 'Select CCPA or GDPR. Default is GDPR.'
                  type: string
                disclosure_type:
                  description: 'Only required if compliance_type = CCPA. Can be Data, Categories, or Sources. Default is Data.'
                  type: string
      tags:
        - Create Retrieval
      summary: Create Retrieval
      description: Creates a data retrieval job.
      responses:
        '200':
          description: Success
        '401':
          $ref: ./common/responses.yaml#/401Unauthorized
        '403':
          $ref: ./common/responses.yaml#/403Forbidden
  /api/app/data-retrievals/v3.0/{tracking_id}:
    parameters:
    - name: tracking_id
      in: path
      schema:
        type: string
      required: true
      description: 'The tracking ID shown in the response'
    get:
      parameters:
      - name: token
        in: query
        description: 'Your project token'
        required: true
        schema:
          type: string
      operationId: get-retrieval
      tags:
        - Check Status of Retrieval
      summary: Check Status of Retrieval
      description: Checks the status of a data retrieval job
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetJobResponse'
        '401':
          $ref: ./common/responses.yaml#/401Unauthorized
        '403':
          $ref: ./common/responses.yaml#/403Forbidden
  /api/app/data-deletions/v3.0:
    post:
      parameters:
      - name: token
        in: query
        description: 'Your project token'
        required: true
        schema:
          type: string
      operationId: create-deletion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                distinct_ids:
                  $ref: '#/components/schemas/DistinctIds'
                compliance_type:
                  description: 'Select CCPA or GDPR. Default is GDPR.'
                  type: string
      tags:
        - Create a Deletion Task
      summary: Create a Deletion Task
      description: Creates a task that specifies a list of users in a particular project to delete
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateDeletionTaskResponse'
        '401':
          $ref: ./common/responses.yaml#/401Unauthorized
        '403':
          $ref: ./common/responses.yaml#/403Forbidden
    delete:
      parameters:
      - name: token
        in: query
        description: 'Your project token'
        required: true
        schema:
          type: string
      operationId: delete-deletion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                distinct_ids:
                  $ref: '#/components/schemas/DistinctIds'
      tags:
        - Delete a Deletion Task
      summary: Delete a Deletion Task
      description: Deletes a task that specifies a list of users in a particular project to delete
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateDeletionTaskResponse'
        '401':
          $ref: ./common/responses.yaml#/401Unauthorized
        '403':
          $ref: ./common/responses.yaml#/403Forbidden
  /api/app/data-deletions/v3.0/{tracking_id}:
    parameters:
    - name: tracking_id
      in: path
      schema: 
        type: string
      required: true
      description: 'The tracking ID shown in the response'
    get:
      parameters:
      - name: token
        in: query
        description: 'Your project token'
        required: true
        schema:
          type: string
      operationId: get-deletion
      tags:
        - Check Status of a Deletion Task
      summary: Check Status of a Deletion Task
      description: Checks the status of an existing deletion task
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteJobResponse'
        '401':
          $ref: ./common/responses.yaml#/401Unauthorized
        '403':
          $ref: ./common/responses.yaml#/403Forbidden
components:
  securitySchemes:
    $ref: ./common/securitySchemes.yaml
  schemas:
    DeleteJobResponse:
      title: DeleteJobResponse
      description: "A JSON response object containing data about a delete job deletion request"
      type: object
      additionalProperties: false
      required:
        - status
        - results
      properties:
        status:
          $ref: '#/components/schemas/ResponseStatus'
        results:
          type: object
          properties:
            task_id: 
              type: string
              description: 'The id of the deletion job.'
    GetJobResponse:
      title: GetJobResponse
      description: "A JSON response object containing data about a data retrieval or deletion job"
      type: object
      additionalProperties: false
      required:
        - status
        - results
      properties:
        status:
          $ref: '#/components/schemas/ResponseStatus'
        results:
          type: object
          properties:
            status:
              type: string
              description: 'The status of the job.'
              enum:
                - PENDING
                - STAGING
                - STARTED
                - SUCCESS
                - FAILURE
                - REVOKED
                - NOT_FOUND
                - UNKNOWN
            results:
              type: string
            distinct_ids:
              $ref: '#/components/schemas/DistinctIds'
    CreateDeletionTaskResponse:
      title: CreateDeletionTaskResponse
      description: "A JSON response object containing data about a data deletion job"
      type: object
      additionalProperties: false
      required:
        - status
        - results
      properties:
        status:
          $ref: '#/components/schemas/ResponseStatus'
        results:
          type: array
          items: 
            $ref: '#/components/schemas/DeletionJobEntry'
    DeletionJobEntry:
      title: DeletionJobEntry
      description: "A deletion job"
      type: object
      additionalProperties: false
      required:
        - status
        - disclosure_type
        - date_requested
        - tracking_id
        - project_id
        - compliance_type
        - destination_url
        - requesting_user
        - distinct_id_count
      properties:
        status:
          type: string
          description: 'The status of the deletion job.'
          enum:
            - PENDING
            - STAGING
            - STARTED
            - SUCCESS
            - FAILURE
            - REVOKED
            - NOT_FOUND
            - UNKNOWN
        disclosure_type:
          type: string
          description: 'Used if compliance_type = CCPA. Can be Data, Categories, or Sources. Default is Data.'
        date_requested:
          type: string
          description: 'The date the deletion job was requested'
        tracking_id:
          type: string
          description: 'The tracking id of the deletion job'
        project_id:
          type: number
          description: 'The id of the project this deletion job is for'
        compliance_type:
          type: string
          description: 'GDPR or CCPA'
        destination_url:
          type: string
        requesting_user:
          type: string
          description: 'The user that created the deletion job request'
        distinct_id_count:
          type: number
          description: 'The number of distinct_ids on this deletion job'
    ResponseStatus:
      type: string
      description: The status of the response
      example: ok
    DistinctIds:
      type: array
      items:
        type: string
        description: A user distinct id
