openapi: 3.0.2
info:
  title: Warehouse Connectors API
  description: Connect an external warehouse to import events, users, groups, and lookup tables.
  version: 1.0.0
  contact:
    url: https://mixpanel.com/get-support
servers:
  - $ref: ./common/app-api.yaml#/server
security:
  - ServiceAccount: []
tags:
  - name: Run an import
    description: Trigger an import sync via API
paths:
  /projects/{projectId}/warehouse-sources/imports/{importId}/manual-sync:
    put:
      parameters:
        - $ref: ./common/parameters.yaml#/path/projectId
        - $ref: ./common/parameters.yaml#/path/importId
      operationId: run-an-import
      requestBody:
        required: true
        content:
          application/json: {}
      tags:
        - Run an import
      summary: Run an import
      description: >-
        This API endpoint triggers an immediate sync for a given warehouse import.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: "./common/responses.yaml#/ResponseStatusOk"
        "401":
          $ref: "./common/responses.yaml#/401Unauthorized"
        "403":
          $ref: "./common/responses.yaml#/403Forbidden"
        "404":
          $ref: "./common/responses.yaml#/404NotFound"
components:
  securitySchemes:
    $ref: ./common/securitySchemes.yaml
