export default {
    "airship": "Airship",
    "appcues": "Appcues",
    "apptimize": "Apptimize",
    "braze": "Braze",
    "chameleon": "Chameleon",
    "clevertap": "CleverTap",
    "facebook-ads": "Facebook Ads",
    "google-ads": "Google Ads",
    "insider": "Insider",
    "intercom": {
        "title": "Intercom ↗",
        "type": "page",
        "href": "https://www.intercom.com/help/en/articles/299-import-your-mixpanel-contacts",
        "newWindow": true
    },
    "iterable": "Iterable",
    "kameleoon": "Kameleoon",
    "leanplum": "Leanplum",
    "mailchimp": "Mailchimp",
    "marketo": "Marketo",
    "moengage": "MoEngage",
    "onesignal": "OneSignal",
    "salesforce-marketing-cloud": "Salesforce Marketing Cloud",
    "segment": "Segment",
    "taplytics": "Taplytics",
    "vwo": "VWO",
    "webengage": "WebEngage",
    "xtremepush": "Xtremepush"
}
