import { Html, Head, Main, NextScript } from "next/document";
import Script from "next/script";

export default function Document() {
  return (
    <Html>
      <Head />
      <body>
        <Main />
        <NextScript />
        <script>
          {`(function(w,q){w['QualifiedObject']=q;w[q]=w[q]||function(){
(w[q].q=w[q].q||[]).push(arguments)};})(window,'qualified')`}
        </script>
        <script async src="https://js.qualified.com/qualified.js?token=gSDtTCjJ2BozXgw6"></script>
        <script
          async
          src="https://widget.kapa.ai/kapa-widget.bundle.js"
          data-website-id="099b7303-a981-443f-9ec7-4aebdc466fb4"
          data-project-name="Mixpanel"
          data-modal-title-ask-ai="Mixpanel Ask AI"
          data-modal-title-search="Mixpanel Search"
          data-search-mode-enabled="true"
          data-search-result-link-target="_self"
          data-project-color="#1b0b3b"
          data-modal-disclaimer="This is a custom LLM for Mixpanel with access to all developer documentation and API references, blogs, and YouTube content. Please note that answers are generated by AI and may not be fully accurate, so please use your best judgement."
          data-project-logo="https://cdn.mxpnl.com/marketing-site/latest-rc/image/external/mixpanel-dark-purple-brand-mark-2x.png"
          data-modal-example-questions-col-span="6"
          data-modal-open-on-command-k="true"
          data-modal-example-questions="What is the first event I should track?,How do I migrate off Google Analytics?,How do I calculate time spent?,How do I import Snowflake data?"
          data-modal-override-open-class-search="top-nav-search-bar"
          data-search-include-source-names='["Documentation", "Guides"]'
          data-search-show-ask-ai-cta="false"
          data-search-source-group-order='["Documentation", "Guides"]'
          data-modal-command-k-search-mode-default="true"
          data-modal-header-bg-color="#f5f2f2"
          data-switch-bg-color="#f5f2f2"
          data-switch-color="#1b0b3b"
          data-modal-header-border-bottom="2px solid #eae7e7"
          data-search-result-primary-text-color="#1b0b3b"
          data-search-result-secondary-text-color="#626266"
          data-search-result-badge-bg-color="#eae7e7"
          data-search-result-badge-text-color="#626266"
          data-query-input-text-color="#1b0b3b"
          // data-query-input-placeholder-text-color="#1b0b3b"
          data-button-bg-color="#7856FF"
          data-modal-overlay-opacity="0.8"
          data-modal-overlay-bg-color="#242133"
        ></script>
        <script>
          {`(function(){let k=window.Kapa;if(!k){let i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};window.Kapa=i}})();`}
        </script>
        {/* Empty script tag as chrome bug fix, see https://stackoverflow.com/a/42969608/943337 */}
        <script> </script>
      </body>
    </Html>
  );
}
