name: Check Markdown links

on: 
  # let's see how long it takes to run
  # pull_request: {}
  # push:
  #   branches: [ main ]
  workflow_dispatch: {}

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: 'check_md_link_config.json'
        folder-path: 'docs/'
        max-depth: -1
        base-branch: 'main'
        file-extension: '.md, .mdx'
