name: Generate ReadMe Staging 🦉

on:
  # when a PR is created in any branch except main that have made changes to the
  # reference folder, run this workflow
  push:
    branches-ignore:
      - main
  pull_request:
    paths:
      - 'reference/**'

jobs:
  # ////////////////////////////////////////////////////////////////////////
  # Pull Request
  # ////////////////////////////////////////////////////////////////////////

  # Create a new ReadMe Version
  rdme-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo 📚
        uses: actions/checkout@v3

      - name: Run `versions` command
        uses: readmeio/rdme@v8
        with:
          rdme: versions:create ${{ github.event.pull_request.number }} --key=${{ secrets.README_API_KEY }} --fork=v3.26 --main=false --beta=false --deprecated=false --isPublic=true

  # Push branch content onto that ReadMe Version
  rdme-docs:
    runs-on: ubuntu-latest
    needs:
      - rdme-version
    steps:
      - name: Check out repo 📚
        uses: actions/checkout@v3

      - name: Run `docs` command 🚀
        uses: readmeio/rdme@v8
        with:
          rdme: docs ./reference --key=${{ secrets.README_API_KEY }} --version=${{ github.event.pull_request.number }}
